language:   ruby
cache:      bundler
services:
  - redis
script:
  - "bundle exec rspec spec"
  - "bundle exec bundle-audit check --update"
  - "bundle exec brakeman --quiet"
  - "bundle exec rubocop"
notifications:
  email:     false
